//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarId { get; set; }
        public string CarNumber { get; set; }
        public string CarImage { get; set; }
        public decimal CarPrice { get; set; }
        public int BookingStatusId { get; set; }
        public int CarBrandId { get; set; }
        public string CarModel { get; set; }
        public int CarYear { get; set; }
        public int CarCapacity { get; set; }
        public string CarDescription { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
